name: Docker-WAHA-Deploy

on:
  push:
    branches: [ "main", "core", "essencial" ]
  pull_request:
    branches: [ "main", "core", "essencial" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ESTE PASSO AQUI É A CHAVE: Ele cria uma variável 'repo' toda em minúsculo
      - name: Lowercase Repo Name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY@L" >> "${GITHUB_ENV}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Usamos a variável REPO_LOWER que criamos no passo anterior
          tags: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:main
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_OPTIONS=--max-old-space-size=4096

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Lowercase Repo Name for Deploy
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY@L" >> "${GITHUB_ENV}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # No servidor, também usamos o nome em minúsculo
            REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            docker pull ghcr.io/$REPO_LOWER:main
            
            docker stop waha || true
            docker rm waha || true
            
            docker run -d --name waha --restart always -p 3000:3000 ghcr.io/$REPO_LOWER:main
